sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lrgoncalve5/docker-react -f Dockerfile.dev .

#script:
#  - docker run USERNAME/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true lrgoncalve5/docker-react npm run test

